<a href="https://colab.research.google.com/github/gabwst17/python_practice/blob/main/VF_Corp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import auth
auth.authenticate_user()

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
%cd /content/drive/MyDrive/

# Import libraries.
import pandas as pd
import numpy as np
import re

df = pd.read_excel('Test raw file.xlsx')

# Print the DataFrame.
df

/content/drive/MyDrive

,ID,Factory Name,Country,Brand,In Scope,2021 Score,2022 Score
0,19576,Factory A*,Vietnam,Vans | Timberland,Y,37,70
1,18180,Factory B,China,Vans | Dickies,No,61,37
2,17396,Factory C,Vietnam,Dickies | Timberland | Vans,Yes,46,62
3,18395,Factory D,Bangladesh,The North Face | Timberland,Yes,38,60
4,10268,Factory E,India,Timberland,Yes,68,63
5,18600,Factory F,Vietnam,Vans | Timberland,No,47,67
6,17272,Factory_G,Vietnam,Timberland | The North Face,Yes,85,99
7,15189,Factory H,China,The North Face | Timberland,Yes,36,43
8,10636,Factory I,China,Vans | Dickies,N,33,53
9,11210,Factory J.,Bangladesh,The North Face | Timberland,Yes,55,42
10,18395,Factory D,Bangladesh,The North Face | Timberland,Yes,38,60
11,15894,Factory L,China,Vans | Timberland,Yes,84,44
12,12759,Factory M,Vietnam,Timberland | The North Face,No,42,95
13,16375,Factory N,Vietnam,Vans,Yes,43,37
14,11689,Factory AA,Bangladesh,The North Face | Timberland,Yes,99,86
15,11135,Factory P,India,Timberland | Vans,No,72,80
16,10593,Factory Q,India,Dickies,Yes,100,56
17,10521,Factory R,China,Vans | Dickies,Y,31,83
18,10678,Factory S,Bangladesh,The North Face | Timberland,No,36,36
19,14128,Factory T,China,The North Face | Vans,Y,43,82
20,12138,Factory U*,China,Timberland | The North Face,No,73,31
21,11962,_Factory V,China,Timberland,Yes,23,72
22,12903,Factory W..,Bangladesh,Vans | Timberland,N,66,77
23,12449,Factory X,Vietnam,The North Face | Timberland,Yes,40,96
24,18435,Factory Y,India,The North Face | Timberland,Yes,78,98
25,11171,Factory Z,India,Vans | Dickies,Y,99,41
26,11689,Factory AA,Bangladesh,The North Face | Timberland,Yes,99,86
27,17272,Factory G,Vietnam,Timberland | The North Face,Yes,85,99
28,15465,Factory AC,Vietnam,Timberland | The North Face,No,78,24
29,12194,Factory AD,China,Vans,Yes,89,20
30,12336,Factory AE,India,Dickies | Vans,Y,31,21
31,12944,Factory AF,Bangladesh,Timberland | Vans,Yes,92,87
32,14557,Factory AG,China,Dickies,Yes,62,45
33,12555,Factory AH,India,The North Face,N,68,27
34,10918,_Factory AI,Bangladesh,Timberland,N,38,90
35,10526,Factory AJ.,Vietnam,Vans | Timberland,No,71,89
36,17533,Factory AKâ€¦,Bangladesh,Timberland | The North Face,Yes,39,58
37,11763,Factory AM,China,Dickies | Vans,Yes,97,55
38,14766,Factory AN,India,Timberland | Vans,No,86,88
39,18304,Factory AO,India,The North Face | Timberland,Yes,83,85
40,17820,Factory AP,China,Vans | Dickies,Yes,43,84
41,14982,Factory AQ,China,The North Face | Timberland,Yes,85,70
42,19845,Factory AR,India,Timberland,Y,60,53
43,13891,Factory AS,Bangladesh,Vans | Dickies,Yes,75,55
44,17182,Factory AT,Vietnam,The North Face | Timberland,No,30,88
45,11452,Factory AU,China,Vans | Timberland,No,59,57
46,16159,Factory AV/,Bangladesh,Timberland | The North Face,Yes,81,20
47,16295,Factory AW,China,Vans,Y,99,96
48,13844,Factory AX,Bangladesh,Timberland,Yes,39,49
49,16558,Factory AL,China,Vans,Yes,86,83

In [4]:
# check data types
# no null info
df.info()
df['Factory Name'] = df['Factory Name'].astype(str)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            50 non-null     int64
 1   Factory Name  50 non-null     object
 2   Country       50 non-null     object
 3   Brand         50 non-null     object
 4   In Scope      50 non-null     object
 5   2021 Score    50 non-null     int64
 6   2022 Score    50 non-null     int64
dtypes: int64(3), object(4)
memory usage: 2.9+ KB

In [5]:
# Question 1.1,drop and recheck for duplicated values
df = df.drop_duplicates()
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [6]:
#Question 1.2, clean up factory name
def remove_symbols(factory_name):
  clean_factory_name = re.sub(r'[^a-zA-Z0-9]', '', factory_name)

  return clean_factory_name

df['Factory Name'] = df['Factory Name'].apply(remove_symbols)
df

<ipython-input-6-128b0668a385>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Factory Name'] = df['Factory Name'].apply(remove_symbols)

,ID,Factory Name,Country,Brand,In Scope,2021 Score,2022 Score
0,19576,FactoryA,Vietnam,Vans | Timberland,Y,37,70
1,18180,FactoryB,China,Vans | Dickies,No,61,37
2,17396,FactoryC,Vietnam,Dickies | Timberland | Vans,Yes,46,62
3,18395,FactoryD,Bangladesh,The North Face | Timberland,Yes,38,60
4,10268,FactoryE,India,Timberland,Yes,68,63
5,18600,FactoryF,Vietnam,Vans | Timberland,No,47,67
6,17272,FactoryG,Vietnam,Timberland | The North Face,Yes,85,99
7,15189,FactoryH,China,The North Face | Timberland,Yes,36,43
8,10636,FactoryI,China,Vans | Dickies,N,33,53
9,11210,FactoryJ,Bangladesh,The North Face | Timberland,Yes,55,42
11,15894,FactoryL,China,Vans | Timberland,Yes,84,44
12,12759,FactoryM,Vietnam,Timberland | The North Face,No,42,95
13,16375,FactoryN,Vietnam,Vans,Yes,43,37
14,11689,FactoryAA,Bangladesh,The North Face | Timberland,Yes,99,86
15,11135,FactoryP,India,Timberland | Vans,No,72,80
16,10593,FactoryQ,India,Dickies,Yes,100,56
17,10521,FactoryR,China,Vans | Dickies,Y,31,83
18,10678,FactoryS,Bangladesh,The North Face | Timberland,No,36,36
19,14128,FactoryT,China,The North Face | Vans,Y,43,82
20,12138,FactoryU,China,Timberland | The North Face,No,73,31
21,11962,FactoryV,China,Timberland,Yes,23,72
22,12903,FactoryW,Bangladesh,Vans | Timberland,N,66,77
23,12449,FactoryX,Vietnam,The North Face | Timberland,Yes,40,96
24,18435,FactoryY,India,The North Face | Timberland,Yes,78,98
25,11171,FactoryZ,India,Vans | Dickies,Y,99,41
27,17272,FactoryG,Vietnam,Timberland | The North Face,Yes,85,99
28,15465,FactoryAC,Vietnam,Timberland | The North Face,No,78,24
29,12194,FactoryAD,China,Vans,Yes,89,20
30,12336,FactoryAE,India,Dickies | Vans,Y,31,21
31,12944,FactoryAF,Bangladesh,Timberland | Vans,Yes,92,87
32,14557,FactoryAG,China,Dickies,Yes,62,45
33,12555,FactoryAH,India,The North Face,N,68,27
34,10918,FactoryAI,Bangladesh,Timberland,N,38,90
35,10526,FactoryAJ,Vietnam,Vans | Timberland,No,71,89
36,17533,FactoryAK,Bangladesh,Timberland | The North Face,Yes,39,58
37,11763,FactoryAM,China,Dickies | Vans,Yes,97,55
38,14766,FactoryAN,India,Timberland | Vans,No,86,88
39,18304,FactoryAO,India,The North Face | Timberland,Yes,83,85
40,17820,FactoryAP,China,Vans | Dickies,Yes,43,84
41,14982,FactoryAQ,China,The North Face | Timberland,Yes,85,70
42,19845,FactoryAR,India,Timberland,Y,60,53
43,13891,FactoryAS,Bangladesh,Vans | Dickies,Yes,75,55
44,17182,FactoryAT,Vietnam,The North Face | Timberland,No,30,88
45,11452,FactoryAU,China,Vans | Timberland,No,59,57
46,16159,FactoryAV,Bangladesh,Timberland | The North Face,Yes,81,20
47,16295,FactoryAW,China,Vans,Y,99,96
48,13844,FactoryAX,Bangladesh,Timberland,Yes,39,49
49,16558,FactoryAL,China,Vans,Yes,86,83

In [7]:
# Question 1.3 Split brand using delimiter and drop old column
df[['Brand1','Brand2','Brand3']] = df['Brand'].str.split("|", expand=True)
df.drop('Brand',axis=1,inplace=True)
df

<ipython-input-7-31c95b0dac72>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Brand1','Brand2','Brand3']] = df['Brand'].str.split("|", expand=True)
<ipython-input-7-31c95b0dac72>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Brand1','Brand2','Brand3']] = df['Brand'].str.split("|", expand=True)
<ipython-input-7-31c95b0dac72>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Brand1','Brand2','Brand3']] = df['Brand'].str.split("|", expand=True)
<ipython-input-7-31c95b0dac72>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Brand',axis=1,inplace=True)

,ID,Factory Name,Country,In Scope,2021 Score,2022 Score,Brand1,Brand2,Brand3
0,19576,FactoryA,Vietnam,Y,37,70,Vans,Timberland,None
1,18180,FactoryB,China,No,61,37,Vans,Dickies,None
2,17396,FactoryC,Vietnam,Yes,46,62,Dickies,Timberland,Vans
3,18395,FactoryD,Bangladesh,Yes,38,60,The North Face,Timberland,None
4,10268,FactoryE,India,Yes,68,63,Timberland,None,None
5,18600,FactoryF,Vietnam,No,47,67,Vans,Timberland,None
6,17272,FactoryG,Vietnam,Yes,85,99,Timberland,The North Face,None
7,15189,FactoryH,China,Yes,36,43,The North Face,Timberland,None
8,10636,FactoryI,China,N,33,53,Vans,Dickies,None
9,11210,FactoryJ,Bangladesh,Yes,55,42,The North Face,Timberland,None
11,15894,FactoryL,China,Yes,84,44,Vans,Timberland,None
12,12759,FactoryM,Vietnam,No,42,95,Timberland,The North Face,None
13,16375,FactoryN,Vietnam,Yes,43,37,Vans,None,None
14,11689,FactoryAA,Bangladesh,Yes,99,86,The North Face,Timberland,None
15,11135,FactoryP,India,No,72,80,Timberland,Vans,None
16,10593,FactoryQ,India,Yes,100,56,Dickies,None,None
17,10521,FactoryR,China,Y,31,83,Vans,Dickies,None
18,10678,FactoryS,Bangladesh,No,36,36,The North Face,Timberland,None
19,14128,FactoryT,China,Y,43,82,The North Face,Vans,None
20,12138,FactoryU,China,No,73,31,Timberland,The North Face,None
21,11962,FactoryV,China,Yes,23,72,Timberland,None,None
22,12903,FactoryW,Bangladesh,N,66,77,Vans,Timberland,None
23,12449,FactoryX,Vietnam,Yes,40,96,The North Face,Timberland,None
24,18435,FactoryY,India,Yes,78,98,The North Face,Timberland,None
25,11171,FactoryZ,India,Y,99,41,Vans,Dickies,None
27,17272,FactoryG,Vietnam,Yes,85,99,Timberland,The North Face,None
28,15465,FactoryAC,Vietnam,No,78,24,Timberland,The North Face,None
29,12194,FactoryAD,China,Yes,89,20,Vans,None,None
30,12336,FactoryAE,India,Y,31,21,Dickies,Vans,None
31,12944,FactoryAF,Bangladesh,Yes,92,87,Timberland,Vans,None
32,14557,FactoryAG,China,Yes,62,45,Dickies,None,None
33,12555,FactoryAH,India,N,68,27,The North Face,None,None
34,10918,FactoryAI,Bangladesh,N,38,90,Timberland,None,None
35,10526,FactoryAJ,Vietnam,No,71,89,Vans,Timberland,None
36,17533,FactoryAK,Bangladesh,Yes,39,58,Timberland,The North Face,None
37,11763,FactoryAM,China,Yes,97,55,Dickies,Vans,None
38,14766,FactoryAN,India,No,86,88,Timberland,Vans,None
39,18304,FactoryAO,India,Yes,83,85,The North Face,Timberland,None
40,17820,FactoryAP,China,Yes,43,84,Vans,Dickies,None
41,14982,FactoryAQ,China,Yes,85,70,The North Face,Timberland,None
42,19845,FactoryAR,India,Y,60,53,Timberland,None,None
43,13891,FactoryAS,Bangladesh,Yes,75,55,Vans,Dickies,None
44,17182,FactoryAT,Vietnam,No,30,88,The North Face,Timberland,None
45,11452,FactoryAU,China,No,59,57,Vans,Timberland,None
46,16159,FactoryAV,Bangladesh,Yes,81,20,Timberland,The North Face,None
47,16295,FactoryAW,China,Y,99,96,Vans,None,None
48,13844,FactoryAX,Bangladesh,Yes,39,49,Timberland,None,None
49,16558,FactoryAL,China,Yes,86,83,Vans,None,None

In [8]:
# Question 1.4 Standardize the In Scope data
df['In Scope'] = df['In Scope'].replace({'Yes': 'Y', 'No': 'N'})
df

<ipython-input-8-fae6db1c1cd7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['In Scope'] = df['In Scope'].replace({'Yes': 'Y', 'No': 'N'})

,ID,Factory Name,Country,In Scope,2021 Score,2022 Score,Brand1,Brand2,Brand3
0,19576,FactoryA,Vietnam,Y,37,70,Vans,Timberland,None
1,18180,FactoryB,China,N,61,37,Vans,Dickies,None
2,17396,FactoryC,Vietnam,Y,46,62,Dickies,Timberland,Vans
3,18395,FactoryD,Bangladesh,Y,38,60,The North Face,Timberland,None
4,10268,FactoryE,India,Y,68,63,Timberland,None,None
5,18600,FactoryF,Vietnam,N,47,67,Vans,Timberland,None
6,17272,FactoryG,Vietnam,Y,85,99,Timberland,The North Face,None
7,15189,FactoryH,China,Y,36,43,The North Face,Timberland,None
8,10636,FactoryI,China,N,33,53,Vans,Dickies,None
9,11210,FactoryJ,Bangladesh,Y,55,42,The North Face,Timberland,None
11,15894,FactoryL,China,Y,84,44,Vans,Timberland,None
12,12759,FactoryM,Vietnam,N,42,95,Timberland,The North Face,None
13,16375,FactoryN,Vietnam,Y,43,37,Vans,None,None
14,11689,FactoryAA,Bangladesh,Y,99,86,The North Face,Timberland,None
15,11135,FactoryP,India,N,72,80,Timberland,Vans,None
16,10593,FactoryQ,India,Y,100,56,Dickies,None,None
17,10521,FactoryR,China,Y,31,83,Vans,Dickies,None
18,10678,FactoryS,Bangladesh,N,36,36,The North Face,Timberland,None
19,14128,FactoryT,China,Y,43,82,The North Face,Vans,None
20,12138,FactoryU,China,N,73,31,Timberland,The North Face,None
21,11962,FactoryV,China,Y,23,72,Timberland,None,None
22,12903,FactoryW,Bangladesh,N,66,77,Vans,Timberland,None
23,12449,FactoryX,Vietnam,Y,40,96,The North Face,Timberland,None
24,18435,FactoryY,India,Y,78,98,The North Face,Timberland,None
25,11171,FactoryZ,India,Y,99,41,Vans,Dickies,None
27,17272,FactoryG,Vietnam,Y,85,99,Timberland,The North Face,None
28,15465,FactoryAC,Vietnam,N,78,24,Timberland,The North Face,None
29,12194,FactoryAD,China,Y,89,20,Vans,None,None
30,12336,FactoryAE,India,Y,31,21,Dickies,Vans,None
31,12944,FactoryAF,Bangladesh,Y,92,87,Timberland,Vans,None
32,14557,FactoryAG,China,Y,62,45,Dickies,None,None
33,12555,FactoryAH,India,N,68,27,The North Face,None,None
34,10918,FactoryAI,Bangladesh,N,38,90,Timberland,None,None
35,10526,FactoryAJ,Vietnam,N,71,89,Vans,Timberland,None
36,17533,FactoryAK,Bangladesh,Y,39,58,Timberland,The North Face,None
37,11763,FactoryAM,China,Y,97,55,Dickies,Vans,None
38,14766,FactoryAN,India,N,86,88,Timberland,Vans,None
39,18304,FactoryAO,India,Y,83,85,The North Face,Timberland,None
40,17820,FactoryAP,China,Y,43,84,Vans,Dickies,None
41,14982,FactoryAQ,China,Y,85,70,The North Face,Timberland,None
42,19845,FactoryAR,India,Y,60,53,Timberland,None,None
43,13891,FactoryAS,Bangladesh,Y,75,55,Vans,Dickies,None
44,17182,FactoryAT,Vietnam,N,30,88,The North Face,Timberland,None
45,11452,FactoryAU,China,N,59,57,Vans,Timberland,None
46,16159,FactoryAV,Bangladesh,Y,81,20,Timberland,The North Face,None
47,16295,FactoryAW,China,Y,99,96,Vans,None,None
48,13844,FactoryAX,Bangladesh,Y,39,49,Timberland,None,None
49,16558,FactoryAL,China,Y,86,83,Vans,None,None

In [9]:
#Question 1.5, remove In Scope = 'N'
df = df[df['In Scope'] != 'N']
df

,ID,Factory Name,Country,In Scope,2021 Score,2022 Score,Brand1,Brand2,Brand3
0,19576,FactoryA,Vietnam,Y,37,70,Vans,Timberland,None
2,17396,FactoryC,Vietnam,Y,46,62,Dickies,Timberland,Vans
3,18395,FactoryD,Bangladesh,Y,38,60,The North Face,Timberland,None
4,10268,FactoryE,India,Y,68,63,Timberland,None,None
6,17272,FactoryG,Vietnam,Y,85,99,Timberland,The North Face,None
7,15189,FactoryH,China,Y,36,43,The North Face,Timberland,None
9,11210,FactoryJ,Bangladesh,Y,55,42,The North Face,Timberland,None
11,15894,FactoryL,China,Y,84,44,Vans,Timberland,None
13,16375,FactoryN,Vietnam,Y,43,37,Vans,None,None
14,11689,FactoryAA,Bangladesh,Y,99,86,The North Face,Timberland,None
16,10593,FactoryQ,India,Y,100,56,Dickies,None,None
17,10521,FactoryR,China,Y,31,83,Vans,Dickies,None
19,14128,FactoryT,China,Y,43,82,The North Face,Vans,None
21,11962,FactoryV,China,Y,23,72,Timberland,None,None
23,12449,FactoryX,Vietnam,Y,40,96,The North Face,Timberland,None
24,18435,FactoryY,India,Y,78,98,The North Face,Timberland,None
25,11171,FactoryZ,India,Y,99,41,Vans,Dickies,None
27,17272,FactoryG,Vietnam,Y,85,99,Timberland,The North Face,None
29,12194,FactoryAD,China,Y,89,20,Vans,None,None
30,12336,FactoryAE,India,Y,31,21,Dickies,Vans,None
31,12944,FactoryAF,Bangladesh,Y,92,87,Timberland,Vans,None
32,14557,FactoryAG,China,Y,62,45,Dickies,None,None
36,17533,FactoryAK,Bangladesh,Y,39,58,Timberland,The North Face,None
37,11763,FactoryAM,China,Y,97,55,Dickies,Vans,None
39,18304,FactoryAO,India,Y,83,85,The North Face,Timberland,None
40,17820,FactoryAP,China,Y,43,84,Vans,Dickies,None
41,14982,FactoryAQ,China,Y,85,70,The North Face,Timberland,None
42,19845,FactoryAR,India,Y,60,53,Timberland,None,None
43,13891,FactoryAS,Bangladesh,Y,75,55,Vans,Dickies,None
46,16159,FactoryAV,Bangladesh,Y,81,20,Timberland,The North Face,None
47,16295,FactoryAW,China,Y,99,96,Vans,None,None
48,13844,FactoryAX,Bangladesh,Y,39,49,Timberland,None,None
49,16558,FactoryAL,China,Y,86,83,Vans,None,None

In [12]:
#Question 1.6 Save to excel
df.to_excel('Gabriel Cleaned Test.xlsx', index=False)